import { describe, expect, it } from 'vitest'
import { replaceRemotes } from './sync.js'

const template = `export default defineConfig({
  plugins: [
    federation({
      name: 'shellApp',
      // Remotes will be auto-populated by mfe-forge sync
      remotes: {
      },
      shared: { react: { singleton: true } },
    }),
  ],
})
`

const entries = `        cartApp: 'http://localhost:3001/assets/remoteEntry.js',\n`

describe('replaceRemotes', () => {
  it('fills the remotes block generated by the host template', () => {
    const { updated, matched } = replaceRemotes(template, entries)

    expect(matched).toBe(true)
    expect(updated).toContain(`remotes: {\n${entries}      },`)
    expect(updated).toContain('shared: { react: { singleton: true } }')
  })

  it('is idempotent when applied repeatedly', () => {
    const once = replaceRemotes(template, entries).updated
    const twice = replaceRemotes(once, entries).updated

    expect(twice).toBe(once)
    expect(twice.match(/cartApp:/g)).toHaveLength(1)
  })

  it('replaces previously registered remotes instead of appending', () => {
    const withOld = replaceRemotes(template, `        oldApp: 'http://localhost:3009/assets/remoteEntry.js',\n`).updated
    const { updated } = replaceRemotes(withOld, entries)

    expect(updated).not.toContain('oldApp')
    expect(updated).toContain('cartApp')
  })

  it('reports no match and leaves content untouched when there is no remotes block', () => {
    const content = `export default defineConfig({ plugins: [] })\n`
    const result = replaceRemotes(content, entries)

    expect(result).toEqual({ updated: content, matched: false })
  })
})
