import { Command } from 'commander'
import chalk from 'chalk'
import fs from 'fs-extra'
import path from 'path'
import { getProjectContext } from '../utils/config.js'
import { discoverApps, discoverHosts } from '../utils/discovery.js'
import { writeManifest } from '../utils/manifest.js'

interface Change { file: string; changed: boolean; reason: string }
function replaceRemotes(content: string, entries: string): string {
  const marker = /remotes:\s*\{[\s\S]*?\n\s*\},/
  const block = `remotes: {\n${entries}      },`
  return marker.test(content) ? content.replace(marker, block) : content
}

export const syncCommand = new Command('sync')
  .description('Synchronize federation declarations, hosts, routes, and manifest')
  .option('--types', 'Generate TypeScript declarations')
  .option('--hosts', 'Sync host federation configuration')
  .option('--routes', 'Sync route metadata')
  .option('--dry-run', 'Show changes without writing')
  .option('--diff', 'Show file changes')
  .option('--check', 'Fail when synchronization is needed')
  .option('--json', 'Output JSON')
  .action(async (options) => {
    const context = getProjectContext(); const apps=discoverApps(context); const hosts=discoverHosts(context)
    const changes: Change[]=[]
    for (const hostName of hosts) {
      const scope=hostName.split('/')[0]; const remotes=apps.filter(app=>app.scope===scope && app.name!==hostName)
      const vitePath=path.join(context.appsDir, hostName, 'vite.config.ts')
      if (options.hosts || (!options.types && !options.routes)) {
        const old=await fs.readFile(vitePath, 'utf8'); const entries=remotes.map(app=>`        ${app.federationName}: 'http://localhost:${app.port}/assets/remoteEntry.js',\n`).join(''); const next=replaceRemotes(old, entries)
        changes.push({ file: path.relative(context.rootDir, vitePath), changed: old!==next, reason: 'federation remotes' }); if (!options.dryRun && old!==next) await fs.writeFile(vitePath,next)
      }
      if (options.types || (!options.hosts && !options.routes)) {
        const declPath=path.join(context.appsDir, hostName, 'src/remotes/declarations.d.ts'); const old=await fs.pathExists(declPath)?await fs.readFile(declPath,'utf8'):''
        const next='// Auto-generated by mfe-forge sync. Do not edit.\n'+remotes.map(app=>`\ndeclare module '${app.federationName}/App' {\n  import React from 'react'\n  const App: React.ComponentType<Record<string, unknown>>\n  export default App\n}\n`).join('')
        changes.push({ file:path.relative(context.rootDir,declPath), changed:old!==next, reason:'remote declarations' }); if (!options.dryRun && old!==next) { await fs.ensureDir(path.dirname(declPath)); await fs.writeFile(declPath,next) }
      }
      if (options.routes) changes.push({ file:path.relative(context.rootDir,path.join(context.appsDir,hostName,'src/App.tsx')), changed:false, reason:'route metadata is represented in the manifest' })
    }
    if (!options.dryRun) await writeManifest(context)
    const changed=changes.filter(item=>item.changed)
    if (options.json) console.log(JSON.stringify({ changed, files: changes, dryRun:Boolean(options.dryRun) }, null, 2))
    else { for (const item of changes.filter(item=>!options.diff || item.changed)) console.log(`${item.changed?'updated':'ok'} ${item.file} (${item.reason})`); console.log(changed.length ? chalk.green(`\nSync ${options.dryRun?'would update':'updated'} ${changed.length} file(s)`) : chalk.green('\nSync is up to date')) }
    if (options.check && changed.length) process.exitCode=1
  })
